language: python
sudo: required
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
env:
  - DJANGO="<2.1"
  - DJANGO="<2.2"
  - DJANGO="<2.3"
before_install:
  - export DJANGO_SETTINGS_MODULE=jet.tests.settings
install:
  - pip install -q "Django${DJANGO}"
  - pip install .
  - pip install coverage==3.7.1
  - pip install coveralls==0.5
script:
  - coverage run --source=jet --omit=*/migrations/*,*/south_migrations/*,*/tests/* manage.py test jet
after_success:
  - coverage report
  - coveralls
